apiVersion: v1
kind: Service
metadata:
  name: service-userprofileservice
spec:
  selector:
    app: pod-userprofileservice 
  type: LoadBalancer
  ports:
  - name: loadbalancer-userprofileservice
    port: 9093
    targetPort: 9093