apiVersion: v1
kind: Service
metadata:
  name: service-gateway
spec:
  selector:
    app: pod-apigateway 
  type: LoadBalancer
  ports:
  - name: loadbalancer-gateway
    port: 80
    targetPort: 80

    