server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/selcukdurukan/MSMaSpringD87CloudConfigRepoYmlGC"
          default-label: main
          skip-ssl-validation: true
          username: selcukdurukan@outlook.com.tr
          password: ${GIT_KEY}
