apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mongodb
  labels:
    name: dep-mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: pod-mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        resources:
          limits:
            memory: "1024Mi"
            cpu: "200m"
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "root"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "root"
          