apiVersion: v1
kind: Service
metadata:
  name: service-configserver
spec:
  selector:
    app: pod-configserver
  type: ClusterIP
  ports:
  - name: loadbalancer-configserver
    port: 8888
    targetPort: 8888
