apiVersion: v1
kind: Service
metadata:
  name: service-mongodb
spec:
  selector:
    app: pod-mongodb 
  type: LoadBalancer
  ports:
  - name: loadbalancer-mongodb
    port: 27777
    targetPort: 27017

    