apiVersion: v1
kind: Service
metadata:
  name: service-authservice
spec:
  selector:
    app: pod-authservice 
  type: LoadBalancer
  ports:
  - name: loadbalancer-authservice
    port: 9090
    targetPort: 9090