#Spring-ZİPKİN sonradan, zipkini uygulamay koymak için yazıldı.

server:
  port: 9090
#  port: ${AUTH_PORT}

spring:
  security:
    user:
      name: java4
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: java4
    password: root
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.159.40.216:11222/springMSAuthD87
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

myapplication:
  auth:
    ip: 192.168.1.153
    port: 9090
  user:
    ip: 192.168.1.153
    port: 9093
    feign-url: http://192.168.1.153:9093/v1/dev/userprofile

buuygulama:
  birdeger: "YML dan gelen bir parametre"
  yenibirdeger: "old'a bak."