server:
  port: 7090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springMSAuthD87
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

myapplication:
  auth:
    ip: localhost
    port: 9090
  user:
    ip: localhost
    port: 9093
    feign-url: http://localhost:9093/v1/dev/userprofile

buuygulama:
  birdeger: "YML dan gelen bir parametre"
  yenibirdeger: ${AUTH_VALUE}