#Spring-ZİPKİN sonradan, zipkini uygulamay koymak için yazıldı.

server:
  port: 9091

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springMSProductD87
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
