server:
  port: 8888

spring:
  security:
    user:
      name: java4
      password: root
  zipkin:
    enabled: true
    base-url: http://10.124.0.32:9411
    service:
      name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
