
# Zipkinden önce config-server.
# Tüm service yml'lerine diğer application.yml'daki farklılıklar girildi.
server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
